baseURL: https://pinar-portfolio.netlify.app/
languageCode: en-us
title: Pinar
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Are you excited to learn about me and my data analytics work?
    title: Hi, my name is Pinar!
  blog: {}
  contact:
    address:
      - city: London, NW1 4SA
        country: UK
        street: Regent's Park
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: pkatircioglu.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +44 737 9255449
        title: Contact Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Pinar
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com/PinarKatirc
#     - icon: fa-facebook
#       label: Facebook
#       url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/pinarkatircioglu1/
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/pkatircioglu
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/pinar-katircioglu
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: PORTFOLIO WEBSITE
    title: PINAR
  tiles:
    enable: yes
    showcase:
      - image: about.jpg
        subtitle: A short biography
        title: About me
        url: blogs/aboutme
        
      - image: horse.jpg
        subtitle: Explore more about me
        title: My Hobbies & Interests
        url: blogs/hobbies_interests
        
      - image: finance_stock.jpg
        subtitle: An analysis of DIJA Stocks
        title: Risk & Return Analysis 
        url: blogs/risk_return
        
      - image: climate_main.jpg
        title: Climate Change & Temperature Anomalies
        url: blogs/climate_change
        
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
        
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Press get started to explore more about me and my work!"
    title: Learn more
    url: blogs
